name: Idiomatic Development
description: Thoughts on frontend engineering and other things
meta_description: "Chad Hietala's thoughts on frontend development and other web technologies"

markdown: redcarpet
highlighter: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'www.chadhietala.com'
author:         'Chad Hietala'
